"""Shared limits for persisted text fields (RFC / UX)."""

# RFC 5321 maximum total length for email local+domain parts in practice.
MAX_EMAIL_LENGTH = 254

MAX_USER_NAME_LENGTH = 200

MAX_TASK_TITLE_LENGTH = 500

MAX_TASK_DESCRIPTION_LENGTH = 10000

MAX_TASK_PROJECT_LENGTH = 200

MAX_TASK_ASSIGNED_AGENT_LENGTH = 100

MAX_BACKGROUND_JOB_TITLE_LENGTH = 500

MAX_INTEGRATION_DISPLAY_NAME_LENGTH = 512

MAX_INTEGRATION_EXTERNAL_ACCOUNT_ID_LENGTH = 512

MAX_OAUTH_SCOPES_JSON_LENGTH = 8192

MAX_CONVERSATION_TITLE_LENGTH = 500

MAX_MESSAGES_PER_CONVERSATION = 500

MAX_NOTIFICATION_TITLE_LENGTH = 240

MAX_NOTIFICATION_BODY_LENGTH = 4000
